### ISSUE TITLE
Launch sub-orbital mission to test RT-10

### ISSUE THREAD

**Issue by ian471** [qhenckel/KSPCo-op#1]
It would be great if the mission could also escape the atmosphere.

**Comment by qhenckel** [comment]
Suggested craft for KRS-1:
[KRS-1.txt](https://github.com/qhenckel/KSPCo-op/files/243888/KRS-1.txt)

Notes:
This ship hit 81K in testing.  I haven't tested reentry from that height.  The first stage is spin stabilized. the second stage tends to flip if SAS isn't used.

**Comment by ian471** [comment]
Approved for launch.

**Comment by qhenckel** [comment]
Mission was completed successfully.

Resources returned:
Science: 28.4
Funds: 2,404 (for recovered parts)
Reputation: 0

Contract gains:
Science: 7
Funds: 35,779 
Reputation: 15

Notes:
We did not gather science after the splashdown because it was deemed to risky.
