### ISSUE TITLE
Our next contracts

### ISSUE THREAD

**Issue by qhenckel** [qhenckel/KSPCo-op#2]
Proposed contracts:
-  Test RT-5 on the lunch pad (R&D)
-  Test 1.25m Heat Shield landed at Kerbin (O.M.B.)

**Comment by ian471** [comment]
Accepted and executed.

**Comment by qhenckel** [comment]
PT-1 was used to test both parts successfully. 
Cost: 1,524
Funds from recovered parts: 1,516
Funds from contracts: 8,302
Science from contracts: 2
Reputation: +2

Notes: It was pretty cool.
