### ISSUE TITLE
more contracts!

### ISSUE THREAD

**Issue by qhenckel** [qhenckel/KSPCo-op#4]
Suggesting:
Tourism contract from StrutCo
Notes:
All four are sub orbital. TC-1 costs 3,285 and there is a 14,625 pay out for each of the 4 flights.
This means a net profit of 11,340 each.

And
Test TT-38K at launch site from O.M.B.
Notes:
free money.

**Comment by ian471** [comment]
The TT-38K test is approved.

However, I have some stability concerns with the proposed design of the TC-1.
![image](https://cloud.githubusercontent.com/assets/1165999/14976109/a6b9f21a-10bd-11e6-9544-d0f3b898e9db.png)

If further research could improve the design, please submit that request separately.

**Comment by qhenckel** [comment]
The TC-1 first stage is identical to the KRS-1 first stage.  Meaning it is pin stabilized.  We can do more research into other methods of maintaining pitch authority if spinning seems inappropriate for tourists.

**Comment by ian471** [comment]
If marketing spins this right, it could actually enhance the marketability of our tourism business. Let's just keep our research mandate in mind and not let the tourism thing spin out of control.
