### ISSUE TITLE
Better parachutes for the TC-1

### ISSUE THREAD

**Issue by qhenckel** [qhenckel/KSPCo-op#5]
After the maiden voyage of TC-1 an almost deadly flaw has been discovered. The twin capsules don't slowdown enough during reentry for the parachute to be opened safely.  

All pending TC-1 flights have been put on hold.  

We are doing more research into solutions.

**Comment by qhenckel** [comment]
We have done simulations. If we had two Mk12-R drogue chutes on the capsules of the TC-1 that would fix our issues.  

This would require 15 science for the 'Survivability' tech node and 600 funds for the entry fee.  

Where as now our success rate of these tourist missions is about 50% with the drogue chutes it would be in excess of 99%.

**Comment by ian471** [comment]
Research and entry purchase are approved. We should probably add "survivable" to our list of space tourism marketing buzzwords.
